name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Android
      uses: docker://bitriseio/docker-android:latest
    - name: Run ktlint
      run: ./gradlew ktlintCheck
    - name: Run Detekt
      run: ./gradlew detekt
    - name: Run Android Lint
      run: ./gradlew lintDebug
    - name: Run Tests
      run: ./gradlew test
