name: Android CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: setup-android
      uses: msfjarvis/setup-android@0.2
      with:
        gradleTasks: "ktlintCheck detekt lint test"

  danger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        if: github.event_name  == 'pull_request'
      - uses: actions/setup-node@v1
        if: github.event_name  == 'pull_request'
        with:
          node-version: 12.x
      - uses: actions/setup-ruby@v1
        if: github.event_name  == 'pull_request'
        with:
          ruby-version: '2.6'
      - uses: MeilCli/danger-action@master
        if: github.event_name  == 'pull_request'
        with:
          plugins_file: 'Gemfile'
          danger_file: 'Dangerfile'
          danger_id: 'danger-pr'
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
