name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '1.8'

    - name: Setup Android SDK
      env:
        ANDROID_HOME: /opt/android-sdk-linux
        PATH: ${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/tools/bin:${ANDROID_HOME}/platform-tools
      run: |
        apt-get update -qq
        cd /opt \
            && wget -q https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip -O android-sdk-tools.zip \
            && unzip -q android-sdk-tools.zip -d ${ANDROID_HOME} \
            && rm android-sdk-tools.zip
        yes | sdkmanager  --licenses
        touch /root/.android/repositories.cfg
        sdkmanager "emulator" "tools" "platform-tools"
        yes | sdkmanager --update --channel=3
        yes | sdkmanager \
            "platforms;android-29" \
            "build-tools;29.0.2" \
            "build-tools;29.0.1" \
            "build-tools;29.0.0" \
            "system-images;android-29;google_apis;x86" \
            "system-images;android-28;google_apis;x86" \
            "system-images;android-26;google_apis;x86" \
            "system-images;android-25;google_apis;armeabi-v7a" \
            "system-images;android-24;default;armeabi-v7a" \
            "system-images;android-22;default;armeabi-v7a" \
            "extras;android;m2repository" \
            "extras;google;m2repository" \
            "extras;google;google_play_services" \
            "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2" \
            "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.1" \
            "add-ons;addon-google_apis-google-23" \
            "add-ons;addon-google_apis-google-22" \
            "add-ons;addon-google_apis-google-21"

    - name: Run ktlint
      run: ./gradlew ktlintCheck
    - name: Run Detekt
      run: ./gradlew detekt
    - name: Run Android Lint
      run: ./gradlew lintDebug
    - name: Run Tests
      run: ./gradlew test
