name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run ktlint
      run: ./gradlew ktlintCheck
    - name: Run Detekt
      run: ./gradlew detekt
    - name: Run Android Lint
      run: ./gradlew lintDebug
    - name: Run Tests
      run: ./gradlew test
